= Migration Guide from Hibernate Search {from_version_short} to {to_version_short}
Yoann Rodière
:awestruct-layout: project-standard
:awestruct-project: search
:toc:
:toc-placement: preamble
:toc-title: Content
:to_version_short: 6.0
:from_version_short: 5.11
:reference_version_full: 6.0.0.Beta11
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse

Here we are helping you migrate your existing Search application to the latest and greatest.

== Upgrade to Hibernate Search {to_version_short}.x from {from_version_short}.x

The aim of this guide is to assist you migrating
an existing application using any version `{from_version_short}.x` of Hibernate Search
to the latest of the `{to_version_short}.x` series.
If you're looking to migrate different versions see link:/search/documentation/migrate[Hibernate Search migration guides].

NOTE: This document provides pointers for a migration.
It refers to Hibernate Search version `{reference_version_full}`.
If you think something is missing or something does not work, please link:/community[contact us].

[IMPORTANT]
====
Search 6 introduces new APIs, so migrating older projects will be more work than usual.

We provide an additional "migration helper" module
that will allow you to use the Search 5 APIs with Search 6 and a Lucene backend under the hood.
However, this module does not offer full backward compatibility: for some features that changed dramatically,
it may not be possible to use the Search 5 APIs anymore.
See <<migration-helper>> for more information.

Finally, for those who cannot afford to, or do not want to, spend the time required to migrate,
we intend to continue maintenance releases (= bugfixes) of Hibernate Search 5.x:
no end-of-life date has been set at the moment.
====

[[requirements]]
=== Requirements

Hibernate Search 6 is still compatible with both JDK8 and JDK11.

The required versions of dependencies changed:

* The Hibernate ORM mapper now requires Hibernate ORM 5.4.4.Final or later
(5.4.3.Final and earlier won't work correctly).
* The Elasticsearch backend now requires Elasticsearch 5.6, 6.8 or 7.9.
* The Lucene backend now requires Lucene 8.6.

[[maven-coordinates]]
=== Maven coordinates changes

If you pull Hibernate Search artifacts from a Maven repository and you come from Hibernate Search 5,
be aware that just bumping the version number will not be enough:

* the group IDs changed from `org.hibernate` to `org.hibernate.search`
* most of the artifact IDs changed to reflect the new mapper/backend design
* the Lucene integration now requires an explicit dependency instead of being pulled by the engine by default.

Read the link:{hsearch-doc-url-prefix}#getting-started-dependencies[getting started guide, section "dependencies"]
for more information.

[[data-format]]
=== Data format changes

Indexes created with Hibernate Search 5 or earlier are not compatible with Hibernate Search 6.
This goes for embedded-Lucene indexes as well as Elasticsearch indexes.

In order to upgrade an application to Hibernate Search 6, all data must be reindexed.
See link:{hsearch-doc-url-prefix}#mapper-orm-indexing-massindexer[the documentation of the `MassIndexer`]
for instructions.

[[migration-helper]]
=== Migration helper

==== Purpose

Hibernate Search 6 includes a temporary additional "migration helper" module
that provides partial compatibility with Hibernate Search 5 APIs backed by the Hibernate Search 6 implementations.

This module should make migration easier by making sure that code relying on the most-frequently-used APIs
(mapping annotations, search DSL, ...)
continues to compile and run.
The idea is to use the migration helper temporarily to make most of the application code (search queries, ...) work,
making it easier to focus on migrating configuration and to assess the effort required to migrate the remaining code.

[IMPORTANT]
====
The migration helper should not be used in production environments.

It has limitations preventing full compatibility with Hibernate Search 5,
and these limitations will never be addressed.

All APIs defined in the migration helper are deprecated and will be removed in the next major version
of Hibernate Search.
====

==== How to use the migration helper

To use the migration helper, add the following dependency to your project:

[source, XML, subs="+attributes"]
----
<dependency>
   <groupId>org.hibernate.search</groupId>
   <artifactId>hibernate-search-v5migrationhelper-orm</artifactId>
   <version>{reference_version_full}</version>
</dependency>
----

Then, try to recompile your application.
Compilation errors should point you to the most significant API changes that require your immediate attention;
most of the code that still compiles should work as it used to in Hibernate Search 5.

[NOTE]
====
The migration helper only addresses Java API compatibility.
This excludes in particular:

* Configuration properties: they must still be <<configuration,replaced with Search 6 properties>>.
* Data format: data must still be <<data-format,reindexed>>.
====

[[configuration]]
=== Configuration changes

WARNING: This section is still incomplete. To be completed upon the CR or release.

One of the main changes is the addition of the concept of "backend" to the configuration.
The "backend" represents a common set of resources shared between multiple index managers:
thread pools if necessary, a filesystem directory where index files are stored (Lucene),
a HTTP client to reach a remote indexing service (Elasticsearch), ...

You will have to define a named "backend" in your configuration,
and set various backend-scoped properties such as the root index path (for local Lucene indexes)
or the hosts (for Elasticsearch) instead of configuring these at the index level like in Search 5.

Read the link:{hsearch-doc-url-prefix}#getting-started-configuration[getting started guide, section "configuration"]
for a quick introduction,
or the link:{hsearch-doc-url-prefix}#configuration[main "configuration" section of the reference documentation]
for more in-depth information.

[[api]]
=== API changes

WARNING: This section is still incomplete. To be completed upon the CR or release.

A lot of APIs changed. We recommend having a look at
link:{hsearch-doc-url-prefix}#getting-started[the getting started guide] before migrating.

[[factory]]
==== `@Factory`

The `@Factory` annotation does not exist in Hibernate Search 6 anymore.

You are encouraged to rely on a proper dependency injection framework if you need such a feature:
just reference the bean name instead of referencing the bean class in your Hibernate Search mapping/configuration.
See link:{hsearch-doc-url-prefix}#configuration-bean[the section of the documentation about beans in Hibernate Search]
for details and supported DI frameworks.

If you don't use a dependency injection framework,
here are details on how to migrate:

String bridges, field bridges, class bridges::
Use their `*Binder` equivalent in Hibernate Search 6,
which can act as a factory:
link:{hsearch-doc-url-prefix}#mapper-orm-bridge-valuebridge-valuebinder[`ValueBinder`],
link:{hsearch-doc-url-prefix}#mapper-orm-bridge-propertybridge[`PropertyBinder`],
link:{hsearch-doc-url-prefix}#mapper-orm-bridge-typebridge[`TypeBinder`].

Full-text filters::
These no longer exist in Hibernate Search 6.
See link:{hsearch-jira-url-prefix}/HSEARCH-3325[HSEARCH-3325].

Programmatic mapping::
`@Factory` is no longer needed for the programmatic mapping,
since you will pass a callback (link:{hsearch-doc-url-prefix}#_configuring_the_mapping[`HibernateOrmSearchMappingConfigurer`])
instead of passing the mapping directly.
Whatever code was implemented in your factory can be moved to the configurer.

Analysis definition providers::
Analysis definition providers are now called link:{hsearch-doc-url-prefix}#backend-lucene-analysis[analysis configurers],
and as they are just callbacks that are used only once,
the `@Factory` annotation should not be necessary.
Whatever code was implemented in your factory can be moved to the configurer.

[[spi]]
=== SPI changes

Due to the extensive rewrites involved in Hibernate Search 6,
existing integrations relying on Hibernate Search 5 are likely to require a full rewrite.
We will be glad to help, so feel free to link:/community[contact us].

[[behavior]]
=== Behavior changes

WARNING: This section is still incomplete. To be completed upon the CR or release.

==== Indexes can only contain one type

It is no longer possible to map multiple entity types to the same index.
Each index must be mapped to exactly one entity type.

==== No default bridge for `java.util.Class`

There is no longer a builtin, default bridge for `java.util.Class`.

If you need to index a `Class<?>`, you will need to write a
link:{hsearch-doc-url-prefix}#mapper-orm-bridge-valuebridge[custom bridge]
(probably from `Class` to `String`).

Optionally, you can also register your custom bridge as a
link:{hsearch-doc-url-prefix}#mapper-orm-bridge-resolver[default bridge]
so that it is applied automatically and transparently to all fields defined on properties of type `Class`.
